on: [push]

jobs:
  status_checker_job:
    runs-on: ubuntu-latest
    name: Checks the OpenPublishing.Build status check for build warnings
    steps:
    - name: Status checker action step
      id: checkStatus
      uses: gewarren/status-check-description-checker@c44683268411ff6091e05704bd925936ef6c3ee1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
