on: [push]

jobs:
  status_checker_job:
    runs-on: ubuntu-latest
    name: Checks the OpenPublishing.Build status check for build warnings
    steps:
    - name: Status checker action step
      id: checkStatus
      uses: gewarren/status-check-description-checker@39c60da562fef6370d2154ffbaae268e14574361
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
